# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Tutorial-4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-Tutorial-4

pod 'RxSwift'
pod 'RxCocoa'
pod 'SnapKit'
pod 'Then'
pod 'Alamofire'
pod 'Kingfisher'

end
