# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Tutorial-6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-Tutorial-6

pod 'RxSwift'
pod 'RxCocoa'
pod 'ReactorKit'
pod 'SnapKit'
pod 'Then'

end
