# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift-Tutorial-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift-Tutorial-2

pod 'RxSwift'
pod 'RxCocoa'
pod 'Alamofire'

  target 'RxSwift-Tutorial-2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift-Tutorial-2UITests' do
    # Pods for testing
  end

end
